### ISSUE TITLE
Not Working As To Be In MS EDGE

### ISSUE THREAD

**Issue by rajeshsahoo12** [bunnykek/AppleMusic-Formats-Extension#1]
Hi Dev,

I have installed extension on MS EDGE which has latest updates from MS. Tried everything from reloading web page, re-open browser & system reboot.

But the extension does not seems to be working. Any helps on this.

![image](https://github.com/bunnykek/AppleMusic-Formats-Extension/assets/54216637/6b8c20da-ac25-4843-93d1-afbab437faf1)

**Comment by bunnykek** [comment]
Thanks for letting me know. I will look into it and fix it within 3-4 days.

**Comment by rajeshsahoo12** [comment]
> Thanks for letting me know. I will look into it and fix it within 3-4 days.

Thanks alot dev for response. Just to let u know. On CHROME it is working fine. But at times it does not work in 1st time. Had to reload page.

I use MS EDGE browser as it is less memory hungry for my system. Whenever I use CHROME on my PC it just cries.

**Comment by rajeshsahoo12** [comment]
> Thanks for letting me know. I will look into it and fix it within 3-4 days.

Just a suggestion can the formats available fonts can be presented in contrast color. As apple music website theme is in dark. And formats available font is too in BLACK. So, it becomes a bit difficult in read.


![image](https://github.com/bunnykek/AppleMusic-Formats-Extension/assets/54216637/33cf2dae-a651-462f-9726-9db943d81424)

**Comment by bunnykek** [comment]
Its working in EDGE. I just checked. Install it from here https://chromewebstore.google.com/detail/applemusic-formats/bhcgojbdkpjilgdcannomfnpdeohdlbn?hl=en-GB
![image](https://github.com/bunnykek/AppleMusic-Formats-Extension/assets/67633271/a9b41c16-c267-4461-92af-63d0e83beb71)
![image](https://github.com/bunnykek/AppleMusic-Formats-Extension/assets/67633271/505f9cef-ad65-4e32-a411-703e877bbfcf)

**Comment by rajeshsahoo12** [comment]
> Its working in EDGE. I just checked. Install it from here https://chromewebstore.google.com/detail/applemusic-formats/bhcgojbdkpjilgdcannomfnpdeohdlbn?hl=en-GB ![image](https://private-user-images.githubusercontent.com/67633271/310538944-a9b41c16-c267-4461-92af-63d0e83beb71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NDIyODIsIm5iZiI6MTcwOTc0MTk4MiwicGF0aCI6Ii82NzYzMzI3MS8zMTA1Mzg5NDQtYTliNDFjMTYtYzI2Ny00NDYxLTkyYWYtNjNkMGU4M2JlYjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDE2MTk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkNGY2YjM0ZTBjODk2NjRlNTc1ZTU5NWU4NDYwMGNlZTVkMzBjMGQ0NWY1OWY1NDcxZjI3MWEwMzJmNmVmYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L5C7tj5d65lhhPW01h22LkwgzSw8SOrw6ptu8lm9aC0) ![image](https://private-user-images.githubusercontent.com/67633271/310538945-505f9cef-ad65-4e32-a411-703e877bbfcf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NDIyODIsIm5iZiI6MTcwOTc0MTk4MiwicGF0aCI6Ii82NzYzMzI3MS8zMTA1Mzg5NDUtNTA1ZjljZWYtYWQ2NS00ZTMyLWE0MTEtNzAzZTg3N2JiZmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDE2MTk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2NWJhNzU1ZDljNjU4NDQzMzNjMDg3NDcwZTA3ZDk4NzZkZjhiMDk5OWIxNzRiYjUzZTlkNjI4Zjc3Yzg1YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g14sHWUUwSNP6Osk01_1eBSCMs2jeZoCyjARoC_ni68)

Yeah for me it was not working because I was using extension available on MS WEB STORE. But as u told now I installed from CHROME WEB STORE & it started working as expected.

Did not realised that CHROME extension work in MS EDGE as the it is based on same CHROMIUM project.

Anyway thanks for solution & making such wonderful extension.

Just a suggestion it will help many if it is mentioned in README that on MSEDGE install it from CHROME WEB STORE.


![image](https://github.com/bunnykek/AppleMusic-Formats-Extension/assets/54216637/7a62b901-1a28-4be7-bcd4-912b01a192ae)

![image](https://github.com/bunnykek/AppleMusic-Formats-Extension/assets/54216637/ff3119a6-800b-406d-935e-07e0977e39a2)
