### ISSUE TITLE
Apple Music 4K Videos Not Marked

### ISSUE THREAD

**Issue by rajeshsahoo12** [bunnykek/AppleMusic-Formats-Extension#3]
Hi Dev,

I am using your fantastic developed extension apple music formats. But the videos which are in 4K format they are not marked as 4K. I have checked on this 4K video of artist `DRAKE`

![image](https://github.com/bunnykek/AppleMusic-Formats-Extension/assets/54216637/0c293aa4-bd9b-411d-8abd-e86b785b80d7)

`https://music.apple.com/in/music-video/spin-bout-u/1674251945` I have cross checked the availability of video in 4K using this script from this repo `https://github.com/glomatico/gamdl`. And here is the output from terminal. Script shows the video is available in 4K.

![image](https://github.com/bunnykek/AppleMusic-Formats-Extension/assets/54216637/92506ec7-853b-4e53-b027-956e5e8a05b5)

Thanks

**Comment by bunnykek** [comment]
Thanks for raising the issue. I'm looking into it.

**Comment by bunnykek** [comment]
Fixed it. You can either wait for the chrome-store one to update or you can manually install using chrome extension developer option.

**Comment by rajeshsahoo12** [comment]
> Thanks for raising the issue. I'm looking into it.

Thanks. Yeah I use this extension extensively. And I suggest many to use it & it is very useful.

**Comment by rajeshsahoo12** [comment]
> Fixed it. You can either wait for the chrome-store one to update or you can manually install using chrome extension developer option.

How can I update using developer mode..?

**Comment by rajeshsahoo12** [comment]
![image](https://github.com/bunnykek/AppleMusic-Formats-Extension/assets/54216637/6059aae0-5359-4dcc-8f00-ab31e7fb3e99)

**Comment by bunnykek** [comment]
Remove the extension. And then on the top you will see "Load Unpacked".  Use that option to load the downloaded extension.

**Comment by rajeshsahoo12** [comment]
> https://music.apple.com/in/music-video/spin-bout-u/1674251945

Thanks dev. It is working as to be.


![image](https://github.com/bunnykek/AppleMusic-Formats-Extension/assets/54216637/daa83a96-b308-4186-bc76-1e11462337dd)
